application: lgbt-app
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /scripts
  static_dir: scripts

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: .*
  script: lgbt.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
